apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: pancasutresna/multi-client
    context: client
    sync:
      manual:
      - src: '**/*.css'
        dest: .
    docker:
      dockerfile: Dockerfile.dev
  local:
    push: false
deploy:
  kubectl:
    manifests:
    - k8s/client-deployment.yaml