apiVersion: apps/v1
kind: apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector: 
    matchLabels:
      component: web
  template:
    metadata:
      label:
        component: web
    spec:
      containers:
        - name: client
          image: pancasutresna/lentera-client-web
          ports:
            - containerPort: 3000