apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-web-deployment
spec:
  replicas: 3
  selector: 
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client-web
          image: pancasutresna/lentera-client-web
          ports:
            - containerPort: 3000